### ISSUE TITLE
Brush Size

### ISSUE THREAD

**Issue by alvissd** [trung74nguyen/TA10#22]
Tạo 1 bar có chức năng khi kéo sẽ làm tăng/giảm kích thước của cọ
*Note: keyword JScrollBar và phần kích thước trong mã nguồn jwhiteboard\

-- Lộc Mai T142772 --

**Comment by nguyenhuuluan** [comment]
Vừa push lên BrushSize trong #26 

-- Luân Nguyễn T144054 --
