### ISSUE TITLE
Lỗi Brush Color.

### ISSUE THREAD

**Issue by linhhathay** [trung74nguyen/TA10#3]
- Màu cọ không random.
- Chỉ hiển thị màu theo bộ 3 RBB,không hiển thị được màu RGB.

-- Linh Nguyễn T140026 --

**Comment by linhhathay** [comment]
đã sửa xong lỗi brush color

**Comment by linhhathay** [comment]
đã sửa trong #16

**Comment by trung74nguyen** [comment]
Đã kiểm tra.
Việc sửa lỗi đạt yêu cầu

-- Trung Nguyễn T144103 --
