### ISSUE TITLE
Lỗi Title

### ISSUE THREAD

**Issue by alvissd** [trung74nguyen/TA10#4]
Không hiển thị đủ thông tin với những cửa sổ mới

-- Lộc Mai T142772 --

**Comment by ducthinh102** [comment]
Đã sửa lỗi

-- Thịnh Phan T143014 --

**Comment by trung74nguyen** [comment]
Đã kiểm tra.
Việc sửa đạt yêu cầu.

-- Trung Nguyễn T144103 --
