### ISSUE TITLE
Một số biến chưa được gán và lệnh bị lặp

### ISSUE THREAD

**Issue by ducthinh102** [trung74nguyen/TA10#5]
Các biến img,d,gr chưa được gán rỗng
Dòng lệnh 589 và 599 bị lặp

-- Thịnh Phan T143014 --

**Comment by alvissd** [comment]
đã sửa trong #15

**Comment by trung74nguyen** [comment]
Đã kiểm tra
Việc sửa đạt yêu cầu

-- Trung Nguyen T144103 --
