### ISSUE TITLE
Lỗi Draw Function

### ISSUE THREAD

**Issue by ducthinh102** [trung74nguyen/TA10#6]
Chỉ vẽ được trên 1 đường chéo thay vì vẽ tự do trong Drawbox

-- Thinh Phan T143014 --

**Comment by nguyenhuuluan** [comment]
Đã sữa lỗi trong #17 @trung74nguyen

**Comment by trung74nguyen** [comment]
Đã kiểm tra
Việc sửa lỗi đạt yêu cầu

-- Trung Nguyễn T144103 --
