### ISSUE TITLE
Lỗi Clear Button

### ISSUE THREAD

**Issue by nguyenhuuluan** [trung74nguyen/TA10#7]
Không thực hiện việc xóa bản vẽ khi nhấn nút.

-- Luân Nguyễn T144054 --

**Comment by ddthinh1996** [comment]
Đã sửa Clear button.

**Comment by trung74nguyen** [comment]
Đã kiểm tra.
Việc sửa lỗi đạt yêu cầu

-- Trung Nguyễn T144103 --
